import { HttpClient, HttpResponse } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { Pokemon } from '../models/pokemon';

//This autogenerated decorator makes it so that we can inject this service into components
//...thus giving components extra functionality.
@Injectable({
  providedIn: 'root'
})


export class PokemonService {

  //pokemon object to get displayed on our components
  //its default values will get filled when we get a new Pokemon
  pokemon:Pokemon = {
    name:"",
    types: "",
    sprites: ""
  }


  //HTTP calls below---------------------------------------------------

  //we need to inject HttpClient in order to make HTTP requests in this service
  constructor(private http:HttpClient) { }

  //This function will GET Pokemon data from pokeapi
  //Note - we use a GET request to GET a Pokemon object as an observable
  //Note note - remember, we can use observable to get data from a server, whether that's our Java or some external API
  getPokemonFromApi(id:number):Observable<HttpResponse<Pokemon>>{
    return this.http.get("https://pokeapi.co/api/v2/pokemon/" + id + "/", {observe: "response"}) as Observable<HttpResponse<Pokemon>>
  }

  //{observe: "response"} tells your function to get the entire HTTP Response, which includes the Response body and status code
  
  //hypothetical function that would let us make POST requests to the Pokeapi and return the pokemon back

}
