import { Injectable } from '@angular/core';
import { Pokemon } from '../models/pokemon';

//This autogenerated decorator makes it so that we can inject this service into components
//...thus giving components extra functionality.
@Injectable({
  providedIn: 'root'
})


export class PokemonService {

  //pokemon object to get displayed on our components
  //its default values will get filled when we get a new Pokemon
  pokemon:Pokemon = {
    name:"",
    types: "",
    sprite: ""
  }


  //HTTP calls below---------------------------------------------------

  

  constructor() { }

}
